apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-forward-auth
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.{{ required "A valid .Values.subdomain entry required!" .Values.subdomain }}`)
      kind: Rule
      middlewares:
        - name: traefik-forward-auth
          namespace: '{{ .Release.Namespace }}'
      services:
        - name: traefik-forward-auth
          port: 4181
  tls:
    certResolver: "{{ .Values.traefik.resolverName }}"
    domains:
      - main: '{{ required "A valid .Values.subdomain entry required!" .Values.subdomain }}'
        sans:
          - '*.{{ required "A valid .Values.subdomain entry required!" .Values.subdomain }}'
