---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-api-credentials
type: Opaque
stringData:
  apiKey: '{{ required "A valid .Values.digitalocean.credentials entry required!" .Values.digitalocean.credentials }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth-generic-oauth
type: Opaque
stringData:
  clientId: '{{ required "A valid .Values.oauth.clientId entry required!" .Values.oauth.clientId }}'
  clientSecret: '{{ required "A valid .Values.oauth.clientSecret entry required!" .Values.oauth.clientSecret }}'
  cookieSecret: '{{ required "A valid .Values.forwardAuth.cookieSecret entry required!" .Values.forwardAuth.cookieSecret }}'
  cookieSigningSecret: '{{ required "A valid .Values.forwardAuth.cookieSigningSecret entry required!" .Values.forwardAuth.cookieSigningSecret }}'
